name: oracle_boosted_sls
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.3.0=pyhd8ed1ab_0
  - alembic=1.9.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=h7ea286d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h8e9501a_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py310h8e9501a_1
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_osxarm64_openblas
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py310h8e9501a_1005
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2023.5.7=hf0a4a13_0
  - cairo=1.16.0=h73a0509_1014
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2399d43_3
  - cfgv=3.3.1=pyhd8ed1ab_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - chex=0.1.5=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - configparser=5.3.0=pyhd8ed1ab_0
  - contourpy=1.0.6=py310h2887b22_0
  - cryptography=38.0.4=py310hfc83b78_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.33=py310h0f1eb42_0
  - databricks-cli=0.17.4=pyhd8ed1ab_0
  - debugpy=1.6.4=py310h0f1eb42_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - distlib=0.3.6=pyhd8ed1ab_0
  - dm-tree=0.1.7=py310h313beb8_1
  - docker-py=6.0.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_0
  - ffmpeg=5.1.2=gpl_hf318d42_105
  - fftw=3.3.10=nompi_h3046061_106
  - filelock=3.9.0=pyhd8ed1ab_0
  - flask=2.2.2=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py310h8e9501a_1
  - freetype=2.12.1=hd633e50_1
  - fribidi=1.0.10=h27ca646_0
  - gdk-pixbuf=2.42.10=h9bcf4fe_0
  - gettext=0.21.1=h0186832_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.30=pyhd8ed1ab_0
  - glib=2.76.2=ha614eb4_0
  - glib-tools=2.76.2=ha614eb4_0
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - gorilla=0.4.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h9f76cd9_1001
  - graphviz=2.50.0=he1da451_0
  - greenlet=2.0.1=py310h0f1eb42_0
  - gts=0.7.6=h4b6d4d6_2
  - gunicorn=20.1.0=py310hbe9552e_3
  - harfbuzz=4.4.1=hd36a07e_0
  - icu=70.1=h6b3803e_0
  - identify=2.5.11=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - ipykernel=6.19.4=pyh736e0ef_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - isort=5.11.4=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jax=0.4.1=pyhd8ed1ab_0
  - jaxlib=0.3.25=py310h313beb8_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=he4db4b2_2
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py310hbe9552e_8
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=5.1.2=py310hbe9552e_0
  - jupyter_events=0.5.0=pyhd8ed1ab_1
  - jupyter_server=2.0.6=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310h2887b22_1
  - lame=3.100=h1a8c8d9_1003
  - lazy-object-proxy=1.8.0=py310h8e9501a_0
  - lcms2=2.14=h481adae_1
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20220623.0=cxx17_h28b99d4_6
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcxx=16.0.2=h4653b0c_0
  - libdeflate=1.17=h1a8c8d9_0
  - libffi=3.4.2=h3422bc3_5
  - libgd=2.3.3=h14f8a72_1
  - libgfortran=5.0.0=11_3_0_hd922786_27
  - libgfortran5=11.3.0=hdaf2cc0_27
  - libglib=2.76.2=h24e9cb9_0
  - libgrpc=1.51.1=h55edf5b_0
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - librsvg=2.54.4=hb3bd4c3_3
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.5.0=h5dffbdd_2
  - libtool=2.4.7=hb7217d7_0
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.3=h87b0503_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.6=h7cfbb63_0
  - mako=1.2.4=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h8e9501a_2
  - matplotlib=3.6.2=py310hb6292c7_0
  - matplotlib-base=3.6.2=py310h78c5c2f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mlflow=1.2.0=py_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.7=pyhd8ed1ab_0
  - nbconvert-core=7.2.7=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.7=pyhd8ed1ab_0
  - nbformat=5.7.1=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=h63371fa_1
  - nodeenv=1.7.0=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numpy=1.23.5=py310hb93e574_0
  - numpy-base=1.23.5=py310haf87e8b_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openblas=0.3.21=openmp_hf78f355_3
  - openh264=2.3.1=hb7217d7_1
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.1.1=h53f4e23_1
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - optax=0.1.4=pyhd8ed1ab_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.5.2=py310h2b830bf_2
  - pandoc=2.19.2=hce30654_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.7=h7271ec9_0
  - paramiko=2.12.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310h5a7539a_4
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - pre-commit=2.21.0=py310hbe9552e_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - prompt_toolkit=3.0.36=hd8ed1ab_0
  - protobuf=4.21.12=py310h0f1eb42_0
  - psutil=5.9.4=py310h8e9501a_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pyflakes=3.0.1=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pygraphviz=1.9=py310h80987f9_1
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pylama=7.7.1=py_0
  - pylint=2.15.9=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h8e9501a_2
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h8e9501a_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.8=h3ba56d0_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytorch=1.13.1=py3.10_0
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0=py310h8e9501a_5
  - pyzmq=24.0.1=py310hc407298_1
  - querystring_parser=1.2.4=py_0
  - re2=2022.06.01=h9a09cb3_1
  - readline=8.1.2=h46ed386_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scipy=1.9.3=py310h20cbe94_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - simplejson=3.18.1=py310h8e9501a_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=1.4.46=py310h8e9501a_0
  - sqlparse=0.4.3=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py310hf1a086a_2
  - svt-av1=1.4.1=h7ea286d_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.6=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchvision=0.14.1=py310_cpu
  - tornado=6.2=py310h8e9501a_1
  - traitlets=5.8.0=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - ukkonen=1.0.1=py310h2887b22_3
  - unicodedata2=15.0.0=py310h8e9501a_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - virtualenv=20.17.1=py310hbe9552e_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
  - pip:
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - allpairs==2.0.1
      - allpairspy==2.5.0
      - astroid==2.6.6
      - async-timeout==4.0.2
      - black==22.12.0
      - cnfgen==0.9.1
      - dm-haiku==0.0.10.dev0
      - docopt==0.6.2
      - exceptiongroup==1.1.1
      - flake8==6.0.0
      - frozenlist==1.3.3
      - func-timeout==4.3.5
      - iniconfig==2.0.0
      - ipython==8.7.0
      - jmp==0.0.2
      - joblib==1.2.0
      - jraph==0.0.6.dev0
      - jsonargparse==4.21.1
      - maturin==0.14.10
      - memory-profiler==0.61.0
      - moser==0.1.0
      - multidict==6.0.4
      - mypy==0.991
      - mypy-extensions==0.4.3
      - networkx==3.1
      - pathspec==0.10.3
      - pipreqs==0.4.13
      - pluggy==1.0.0
      - pydot==1.4.2
      - pytest==7.3.1
      - python-sat==0.1.7.dev21
      - wrapt==1.12.1
      - yarg==0.1.9
      - yarl==1.8.2
prefix: /Users/p390943/miniforge3/envs/moser
